# Site settings
title: MMelo
email: miguelbritomelo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple front-end webdeveloper's blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mmelo.github.io" # the base hostname & protocol for your site
twitter_username: _mmelo
github_username:  mmelo

# Build settings
markdown: kramdown
